apiVersion: v2
name: laravel
description: A Helm chart for Laravel applications with PHP-FPM, Nginx, MariaDB/PostgreSQL, Redis
type: application
version: 0.2.1
appVersion: "10.41.0"
dependencies:
  - name: postgresql
    version: 13.4.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: 18.8.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
