# Default values for laravel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: laravel
imagePullPolicy: Always

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: { }
  name: ""

podAnnotations: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: { }
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]

resources: { }

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }

database:
  connection: pgsql

queueWorker:
  replicaCount: 1

aws:
  accessKey: "acces-key"
  secretKey: "secret-key"

env:
  APP_NAME: Laravel
  APP_ENV: local
  APP_DEBUG: true
  APP_URL: http://127.0.0.1:8080
  LOG_CHANNEL: stack
  LOG_LEVEL: debug

  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  FILESYSTEM_DISK: local
  QUEUE_CONNECTION: redis
  SESSION_DRIVER: redis
  SESSION_LIFETIME: 120

nginx:
  image: nginx:1.25.3-alpine3.18
  imagePullPolicy: Always
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  podAnnotations: { }
  priorityClassName:

  defaultConf: |
    server {
      listen 80;
      listen [::]:80;
      server_name _;
      root /srv/app/public;
    
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-Content-Type-Options "nosniff";
    
      index index.php;
    
      charset utf-8;
    
      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }
    
      location = /favicon.ico { access_log off; log_not_found off; }
      location = /robots.txt  { access_log off; log_not_found off; }
    
      error_page 404 /index.php;
    
      location ~ \.php$ {
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_read_timeout 300;
          include fastcgi_params;
          fastcgi_intercept_errors on;
      }
    
      location ~ /\.(?!well-known).* {
          deny all;
      }
    }

postgresql:
  enabled: true
  auth:
    username: laravel
    database: laravel
  primary:
    persistence:
      size: 1Gi

redis:
  enabled: true
  architecture: standalone
  master:
    persistence:
      size: 1Gi
