apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: laravel
      context: laravel
      docker:
        dockerfile: Dockerfile
manifests:
  helm:
    releases:
      - name: laravel
        chartPath: ./chart
#        valuesFiles:
#          - laravel/k8s/values.yaml
        setValueTemplates:
          image: '{{.IMAGE_FULLY_QUALIFIED_laravel}}'
          imagePullPolicy: '{{.IMAGE_PULL_POLICY_laravel}}'
        skipBuildDependencies: true
deploy:
  helm: {}
portForward:
  - resourceType: service
    resourceName: laravel-service
    port: 80
    localPort: 8888
