apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: laravel
      context: laravel
      docker:
        dockerfile: Dockerfile
manifests:
  helm:
    releases:
      - name: laravel
        chartPath: ./chart
        setValueTemplates:
          image: '{{.IMAGE_FULLY_QUALIFIED_laravel}}'
          imagePullPolicy: '{{.IMAGE_PULL_POLICY_laravel}}'
          env:
            APP_KEY: base64:scHwFv2TLZkl9n5YCFGTNUg/oUCnGCc69uiOUBWZl/U=
        skipBuildDependencies: true
deploy:
  helm: {}
portForward:
  - resourceType: service
    resourceName: laravel-service
    port: 80
    localPort: 8080
