apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel.fullname" . }}-app-env
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  default.conf: {{ .Values.nginx.defaultConf | quote }}
