apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel.fullname" . }}-app-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretKey | b64enc }}
