apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel.fullname" . }}-app-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
type: Opaque
data: {}
