apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mariadb-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.mariadb.persistence.storageClassName }}
  accessModes: {{ .Values.mariadb.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}
