apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redis-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.redis.persistence.storageClassName }}
  accessModes: {{ .Values.redis.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
