apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.redis.service.port}}
      targetPort: redis
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
